version: "3.2"

services:
  whirlpool:
    image: "samouraiwallet/dojo-whirlpool:${DOJO_WHIRLPOOL_VERSION_TAG}"
    container_name: whirlpool
    build:
      context: ./whirlpool
    env_file:
      - ./.env
      - ./conf/docker-common.conf
      - ./conf/docker-node.conf
      - ./conf/docker-whirlpool.conf
    restart: always
    command: "/wait-for-it.sh nginx:80 --timeout=720 --strict -- /restart.sh"
    expose:
      - "8899"
    volumes:
      - data-whirlpool:/home/whirlpool
    depends_on:
      - nginx
    networks:
      whirlnet:
        ipv4_address: 172.30.1.8

volumes:
  data-whirlpool:
